# Service - LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice
  labels:
    app: jenkinspod
spec:
  selector:
    app: jenkinspod
  type: NodePort
  ports:
  - nodePort: 32750
    port: 8080
    targetPort: 8080