{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "Jenkins.serviceAccountName" . }}
  labels:
{{ include "Jenkins.labels" . | indent 4 }}
{{- end -}}
